SELECT 
    RI.REST_ID,
    RI.REST_NAME,
    RI.FOOD_TYPE,
    (SELECT SUM(FAVORITES) FROM REST_INFO WHERE REST_ID = RI.REST_ID GROUP BY REST_ID) AS FAVORITES,
    RI.ADDRESS,
    ROUND((SELECT AVG(REVIEW_SCORE) FROM REST_REVIEW WHERE REST_ID = RI.REST_ID GROUP BY REST_ID), 2) AS SCORE
FROM REST_INFO RI
JOIN REST_REVIEW RR ON
RI.REST_ID = RR.REST_ID
GROUP BY RI.REST_ID
HAVING RI.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC