-- LINE 호선, NO 순번, ROUTE 노선, STATION_NAME 역 이름, D_BETWEEN_DIST 역사이거리, D_CUMULATIVE 노선별 누계

SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km')  AS TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE FROM SUBWAY_DISTANCE GROUP BY ROUTE ORDER BY SUM(D_BETWEEN_DIST) DESC;