SELECT DISTINCT CCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CCH ON
CCC.CAR_ID = CCH.CAR_ID
WHERE CCC.CAR_TYPE = '세단' AND 
MONTH(START_DATE) = 10 
ORDER BY CAR_ID DESC